# Generated by Django 4.2.7 on 2024-03-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userplan',
            options={'ordering': ['start_date']},
        ),
    ]
