# Generated by Django 4.2.7 on 2024-03-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(help_text='Enter 10 digits phone number', max_length=11, unique=True, verbose_name='Phone Number'),
        ),
    ]
